[menu __main calibrate]
name: Calibrate
icon: fine-tune

[menu __main calibrate bed_mesh]
name: Bed Mesh
icon: bed-level
method: printer.gcode.script
params: {"script":"BED_MESH_CALIBRATE"}

[menu __main calibrate screws]
name: Level Screws
icon: bed-level-manual-step
method: printer.gcode.script
params: {"script":"SCREWS_TILT_ADJUST"}

[menu __main calibrate hot_z]
name: Z Offset Hot
icon: z-offset
method: printer.gcode.script
params: {"script":"CALIBRATE_Z_HOT"}

[menu __main calibrate z_offset]
name: Z Offset
icon: z-offset
method: printer.gcode.script
params: {"script":"PROBE_CALIBRATE"}

[menu __main save_config]
name: Save Config
icon: save
method: printer.gcode.script
params: {"script":"SAVE_CONFIG"}

[preheat PLA]
extruder = 200
heater_bed = 60

[preheat PETG]
extruder = 230
heater_bed = 80

[preheat ABS]
extruder = 240
heater_bed = 100

[menu __main filament]
name: Filament
icon: filament

[menu __main filament load]
name: Load Filament
icon: arrow-up
method: printer.gcode.script
params: {"script":"LOAD_FILAMENT"}

[menu __main filament unload]
name: Unload Filament
icon: arrow-down
method: printer.gcode.script
params: {"script":"UNLOAD_FILAMENT"}

[menu __main home]
name: Home
icon: home
method: printer.gcode.script
params: {"script":"G28"}

[menu __main park]
name: Park
icon: home
method: printer.gcode.script
params: {"script":"PARK"}

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-dark
#~# print_estimate_method = slicer
#~# screen_blanking = off
#~# screen_blanking_printing = off
#~# 24htime = False
#~# font_size = small
#~# confirm_estop = True
#~# use_dpms = False
#~# print_sort_dir = date_desc
#~# 
#~# [graph Printer]
#~# temperature_sensor raspberry_pi = False
#~#
